const { withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Forces `@react-native-firebase` to resolve the Firebase iOS SDK through CocoaPods, not SPM.
 *
 * ## The failure this fixes
 *
 * `pod install` refuses to complete:
 *
 *     [!] [react-native-firebase] SPM + static linkage is not supported (target(s): Pods-Spoon).
 *
 * From react-native-firebase 23 onwards the pods declare Firebase as a Swift Package when React
 * Native supports it. firebase-ios-sdk's SPM products are plain `.library(...)` — automatic
 * linkage, not `type: .dynamic` — so each consuming pod links its own copy. Under
 * `use_frameworks! :linkage => :static` those copies meet at link time as duplicate symbols, and
 * CocoaPods stops rather than producing a binary that would fail later and less legibly.
 *
 * The library documents the escape hatch itself, in `firebase_spm.rb`: "You must disable SPM when
 * using `use_frameworks! :linkage => :static`". `$RNFirebaseDisableSPM = true` selects the
 * CocoaPods dependency path those pods used for years, which is well-trodden rather than novel.
 *
 * ## Why not switch to dynamic linkage instead
 *
 * It is the larger change and the less certain one. Static linkage is here for react-native-maps,
 * and flipping it changes how EVERY native module in the app links — Maps included — to fix a
 * problem that belongs to one dependency. `firebase_spm.rb` also notes that dynamic linkage under
 * SPM still embeds a private Firebase copy per pod, so it avoids the link error without giving
 * the pods a shared FirebaseCore; that is the state this flag exists to provide. Changing one
 * dependency's resolution is a smaller blast radius than changing every module's linkage.
 *
 * ## Why a plugin and not a Podfile edit
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, exactly like `android/`. A Podfile
 * edited by hand survives until the next regeneration — which is the moment nobody is looking for
 * a build setting that has quietly gone. Same reason `withGradleHeap` and `withNdkVersion` exist.
 *
 * The flag is read as a Ruby global at Podfile evaluation time, so it has to be assigned before
 * the target block that triggers the check, and it must be `true` exactly:
 * `rnfirebase_spm_disabled?` tests the VALUE, so that a generator emitting `false` cannot silently
 * switch resolution.
 */

const FLAG = '$RNFirebaseDisableSPM = true';

const BANNER = [
  '# Firebase through CocoaPods rather than SPM.',
  '#',
  '# Required by use_frameworks! :linkage => :static -- under SPM each react-native-firebase pod',
  '# links its own copy of firebase-ios-sdk and they collide as duplicate symbols. Set by the',
  '# withFirebaseCocoaPods config plugin; edit that, not this file, which prebuild regenerates.',
  FLAG,
].join('\n');

module.exports = function withFirebaseCocoaPods(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfile, 'utf8');

      // Idempotent: prebuild may run repeatedly over one ios/ directory.
      if (contents.includes('$RNFirebaseDisableSPM')) return cfg;

      /*
       * Before the first `target` block, which is where the check runs. Anchoring on `target`
       * rather than appending is what makes the assignment happen in time; a global set after the
       * block that reads it is the same as not setting it at all.
       */
      const anchor = contents.search(/^target\s/m);
      if (anchor === -1) {
        throw new Error(
          'withFirebaseCocoaPods: no target block found in the Podfile, so ' +
            `${FLAG} cannot be placed before the check that reads it.`,
        );
      }

      const updated = `${contents.slice(0, anchor)}${BANNER}\n\n${contents.slice(anchor)}`;
      fs.writeFileSync(podfile, updated);
      return cfg;
    },
  ]);
};
