const fs = require('fs');
const path = require('path');
const { withDangerousMod, withMainActivity } = require('expo/config-plugins');

/**
 * Draws the designed launch splash natively on Android, from the first frame, so the flat-yellow
 * system splash is only on screen for process start-up and never while the JS bundle loads.
 *
 * ## Why this exists
 *
 * Android 12+ lets the OS splash be a flat colour and an icon, nothing else. `expo-splash-screen`
 * also holds that splash on screen until JS has rendered (`SplashScreenManager` blocks the first
 * draw until `hide()`), so the customer sat on flat yellow for the whole bundle load -- seconds in
 * a debug build -- before `LaunchSplash` (`src/ui/feedback/LaunchSplash.tsx`) could draw the
 * gradient. That is the "yellow, then the real splash" jump.
 *
 * ## The fix
 *
 * - An `ImageView` of the same artwork `LaunchSplash` uses is added over the activity's content
 *   in `onCreate`, and `SplashScreenManager.hide()` is called straight after, so the first frame
 *   the app draws already has the gradient and the system splash goes away immediately.
 * - The artwork is cover-fitted (React Native's `resizeMode="cover"`) and then shifted so its
 *   letters, which sit at 48% of its height, land at the screen's centre -- where the system
 *   splash centres its logo (`assets/images/splash-wordmark-android.png`). Without the shift the
 *   letters would jump when the artwork takes over. `LaunchSplash` applies the identical
 *   placement; keep the constants in step.
 * - Once React reports its first content (`CONTENT_APPEARED`, which includes `LaunchSplash`
 *   itself), the native view is removed after a short overlap so that, if the JS copy of the
 *   artwork is still decoding, the screen does not flash.
 *
 * The OS splash that shows during process start (before any app code can run) stays flat yellow
 * -- that is an Android limit, not something this can change.
 *
 * ## Why a config plugin
 *
 * `android/` is generated and gitignored -- same reasoning as `withNdkVersion.js`.
 */
const ARTWORK_SOURCE = 'assets/images/splash-background-ios.png';
const ARTWORK_RESOURCE = 'launch_artwork.png';
const MARKER = 'LaunchArtwork.show(this)';

function launchArtworkKotlin(packageName) {
  return `package ${packageName}

import android.app.Activity
import android.graphics.Color
import android.graphics.Matrix
import android.view.ViewGroup
import android.widget.FrameLayout
import android.widget.ImageView
import com.facebook.react.bridge.ReactMarker
import com.facebook.react.bridge.ReactMarkerConstants

// Generated by plugins/withAndroidLaunchArtwork.js -- see the plugin for why this exists.
object LaunchArtwork {
  /** Overlap with the JS \`LaunchSplash\`, so a still-decoding JS image never shows a gap. */
  private const val OVERLAP_MS = 300L

  /** Where the middle of the wordmark's letters sits in the artwork, as a fraction of its height. */
  private const val WORDMARK_CENTRE_Y = 0.4785f

  /** The artwork's top edge colour; fills the strip exposed above the shifted-down artwork. */
  private const val ART_TOP_COLOUR = "#FEE24D"

  fun show(activity: Activity) {
    val content = activity.findViewById<ViewGroup>(android.R.id.content) ?: return
    val art = ImageView(activity).apply {
      setImageResource(R.drawable.launch_artwork)
      scaleType = ImageView.ScaleType.MATRIX
      setBackgroundColor(Color.parseColor(ART_TOP_COLOUR))
      layoutParams = FrameLayout.LayoutParams(
        ViewGroup.LayoutParams.MATCH_PARENT,
        ViewGroup.LayoutParams.MATCH_PARENT
      )
    }
    art.addOnLayoutChangeListener { view, left, top, right, bottom, _, _, _, _ ->
      val image = (view as ImageView).drawable ?: return@addOnLayoutChangeListener
      val width = (right - left).toFloat()
      val height = (bottom - top).toFloat()
      if (width == 0f || height == 0f) return@addOnLayoutChangeListener
      val imageWidth = image.intrinsicWidth.toFloat()
      val imageHeight = image.intrinsicHeight.toFloat()
      val scale = maxOf(width / imageWidth, height / imageHeight)
      view.imageMatrix = Matrix().apply {
        setScale(scale, scale)
        postTranslate(
          (width - imageWidth * scale) / 2f,
          height / 2f - WORDMARK_CENTRE_Y * imageHeight * scale
        )
      }
    }
    content.addView(art)

    lateinit var listener: ReactMarker.MarkerListener
    listener = ReactMarker.MarkerListener { name, _, _ ->
      if (name == ReactMarkerConstants.CONTENT_APPEARED) {
        ReactMarker.removeListener(listener)
        art.postDelayed({ content.removeView(art) }, OVERLAP_MS)
      }
    }
    ReactMarker.addListener(listener)
  }
}
`;
}

module.exports = function withAndroidLaunchArtwork(config) {
  config = withDangerousMod(config, [
    'android',
    (modConfig) => {
      const root = modConfig.modRequest.projectRoot;
      const packageName = modConfig.android?.package;
      if (packageName === undefined) {
        throw new Error('withAndroidLaunchArtwork: android.package is not set');
      }

      const res = path.join(modConfig.modRequest.platformProjectRoot, 'app/src/main/res');
      fs.mkdirSync(path.join(res, 'drawable-nodpi'), { recursive: true });
      fs.copyFileSync(
        path.join(root, ARTWORK_SOURCE),
        path.join(res, 'drawable-nodpi', ARTWORK_RESOURCE),
      );

      const javaDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app/src/main/java',
        ...packageName.split('.'),
      );
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(path.join(javaDir, 'LaunchArtwork.kt'), launchArtworkKotlin(packageName));
      return modConfig;
    },
  ]);

  return withMainActivity(config, (modConfig) => {
    const { contents } = modConfig.modResults;
    if (contents.includes(MARKER)) return modConfig;

    const anchor = 'super.onCreate(null)';
    if (!contents.includes(anchor)) {
      throw new Error(`withAndroidLaunchArtwork: could not find \`${anchor}\` in MainActivity`);
    }
    modConfig.modResults.contents = contents.replace(
      anchor,
      `${anchor}\n    ${MARKER}\n    SplashScreenManager.hide()`,
    );
    return modConfig;
  });
};
